<a href="https://colab.research.google.com/github/HarshAade/DS_AI/blob/main/Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Assignment - Movies Dataset

In [2]:
# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Import the numpy and pandas packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# *Task 1: Reading and Inspection*

-  Subtask 1.1: Import and read

       Import and read the movie database. Store it in a variable called `movies`.
       movies = # Write your code for importing the csv file here movies

In [30]:
movies = pd.read_csv('Movie+Assignment+Data.csv')
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

-  Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.
    
     Write your code for inspection here

In [7]:
# Checking column names
print(movies.columns)

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [8]:
# Checking shape of dataframe
print(movies.shape)

(5043, 28)

In [9]:
# Checking variable types
print(movies.dtypes)

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [11]:
# Watching summary statistics of Data set
print(movies.describe())

       num_critic_for_reviews     duration  director_facebook_likes  \
count             4993.000000  5028.000000              4939.000000
mean               140.194272   107.201074               686.509212
std                121.601675    25.197441              2813.328607
min                  1.000000     7.000000                 0.000000
25%                 50.000000    93.000000                 7.000000
50%                110.000000   103.000000                49.000000
75%                195.000000   118.000000               194.500000
max                813.000000   511.000000             23000.000000

       actor_3_facebook_likes  actor_1_facebook_likes         gross  \
count             5020.000000             5036.000000  4.159000e+03
mean               645.009761             6560.047061  4.846841e+07
std               1665.041728            15020.759120  6.845299e+07
min                  0.000000                0.000000  1.620000e+02
25%                133.000000              614.000000  5.340988e+06
50%                371.500000              988.000000  2.551750e+07
75%                636.000000            11000.000000  6.230944e+07
max              23000.000000           640000.000000  7.605058e+08

       num_voted_users  cast_total_facebook_likes  facenumber_in_poster  \
count     5.043000e+03                5043.000000           5030.000000
mean      8.366816e+04                9699.063851              1.371173
std       1.384853e+05               18163.799124              2.013576
min       5.000000e+00                   0.000000              0.000000
25%       8.593500e+03                1411.000000              0.000000
50%       3.435900e+04                3090.000000              1.000000
75%       9.630900e+04               13756.500000              2.000000
max       1.689764e+06              656730.000000             43.000000

       num_user_for_reviews        budget   title_year  \
count           5022.000000  4.551000e+03  4935.000000
mean             272.770808  3.975262e+07  2002.470517
std              377.982886  2.061149e+08    12.474599
min                1.000000  2.180000e+02  1916.000000
25%               65.000000  6.000000e+06  1999.000000
50%              156.000000  2.000000e+07  2005.000000
75%              326.000000  4.500000e+07  2011.000000
max             5060.000000  1.221550e+10  2016.000000

       actor_2_facebook_likes   imdb_score  aspect_ratio  movie_facebook_likes
count             5030.000000  5043.000000   4714.000000           5043.000000
mean              1651.754473     6.442138      2.220403           7525.964505
std               4042.438863     1.125116      1.385113          19320.445110
min                  0.000000     1.600000      1.180000              0.000000
25%                281.000000     5.800000      1.850000              0.000000
50%                595.000000     6.600000      2.350000            166.000000
75%                918.000000     7.200000      2.350000           3000.000000
max             137000.000000     9.500000     16.000000         349000.000000

In [10]:
# Checking for missing values
print(movies.isnull().sum())

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

# *Task 2: Cleaning the Data*



-  Subtask 2.1: Inspect Null values

    Find out the number of Null values in all the columns and rows.
    Also, find the percentage of Null values in each column.
    Round off the percentages upto two decimal places.


    Write your code for column-wise null count here
    Write your code for row-wise null count here
    Write your code for column-wise null percentages here

In [14]:
# column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [15]:
# for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [16]:
# column-wise null percentages here round by 2
round(100*(movies.isnull().sum()/len(movies.index)), 2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.28
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64


-  Subtask 2.2: Drop unecessary columns

   For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.

----
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords
----
    
    
     Write your code for dropping the columns here.
     It is advised to keep inspecting the dataframe after each set of operations

In [31]:
movies.drop(['color',
                   'director_facebook_likes',
                   'actor_1_facebook_likes',
                   'actor_2_facebook_likes',
                   'actor_3_facebook_likes',
                   'actor_2_name',
                   'cast_total_facebook_likes',
                   'actor_3_name',
                   'duration',
                   'facenumber_in_poster',
                   'content_rating',
                   'country',
                   'movie_imdb_link',
                   'aspect_ratio',
                   'plot_keywords'], axis=1, inplace=True)

In [32]:
movies.head(5)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0

In [33]:
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.28
budget                     9.76
title_year                 2.14
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

-  Subtask 2.3: Drop unecessary rows using columns with high Null percentages

   Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.
  
  
    Write your code for dropping the rows here

In [34]:
movies.drop(['gross', 'budget'], axis=1)
movies[np.isnan(movies['gross'])]
movies[~np.isnan(movies['budget'])]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5036,Anthony Vallone,NaN,NaN,Crime|Drama,Richard Jewell,The Mongol King,36,1.0,English,3250.0,2005.0,7.8,4
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  Subtask 2.4: Drop unecessary rows

   Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.


    Write your code for dropping the rows here

In [35]:
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.28
budget                     9.76
title_year                 2.14
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

In [36]:
movies.drop(movies[movies.isnull().sum(axis=1) > 5].index, inplace=True)

In [37]:
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name              2.02
num_critic_for_reviews     0.91
gross                     17.46
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.34
language                   0.24
budget                     9.68
title_year                 2.06
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

-  Subtask 2.5: Fill NaN values

   You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

   
    Write your code for filling the NaN values in the 'language' column here

In [38]:
movies.loc[pd.isnull(movies['language']), ['language']] = 'English'

In [39]:
movies.language

0       English
1       English
2       English
3       English
5       English
         ...
5038    English
5039    English
5040    English
5041    English
5042    English
Name: language, Length: 5039, dtype: object

-  Subtask 2.6: Check the number of retained rows

   You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

     
    Write your code for checking number of retained rows here

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

In [40]:
print(movies.index)

Index([   0,    1,    2,    3,    5,    6,    7,    8,    9,   10,
       ...
       5033, 5034, 5035, 5036, 5037, 5038, 5039, 5040, 5041, 5042],
      dtype='int64', length=5039)

In [41]:
round(100*(len(movies.index)/len(movies)),2)

100.0

# *Task 3: Data Analysis*

-  Subtask 3.1: Change the unit of columns

   Convert the unit of the `budget` and `gross` columns from `$` to `million $`
   
   
    Write your code for unit conversion here

In [42]:
movies[['gross','budget']].apply(lambda x:x/1000000)

           gross    budget
0     760.505847  237.0000
1     309.404152  300.0000
2     200.074175  245.0000
3     448.130642  250.0000
5      73.058679  263.7000
...          ...       ...
5038         NaN       NaN
5039         NaN       NaN
5040         NaN    0.0014
5041    0.010443       NaN
5042    0.085222    0.0011

[5039 rows x 2 columns]

-  Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`


    # Write your code for creating the profit column here
    # Write your code for sorting the dataframe here

top10 = # Write your code to get the top 10 profiting movies here

In [ ]:
# Write your code for creating the profit column here
movies['profit']=movies['gross'] - movies['budget']
movies.head()

In [44]:
# Write your code for sorting the dataframe here
movies.sort_values(by='profit',ascending=True)
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,9404152.0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,-44925825.0
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,198130642.0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000,-190641321.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84,NaN
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000,NaN
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16,NaN
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660,NaN
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456,84122.0

In [ ]:
sns.catplot(data=movies, x='budget', y='profit')

In [ ]:
# Write your code to get the top 10 profiting movies here
top10=movies.sort_values(by=['profit'],ascending=False).head(10)
top10.head(10)

- Subtask 3.3: Drop duplicate values

   After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.


    # Write your code for dropping duplicate values here
    # Write code for repeating subtask 2 here

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

In [46]:
# Write your code for dropping duplicate values here
movies.drop_duplicates()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,9404152.0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,-44925825.0
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,198130642.0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000,-190641321.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84,NaN
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000,NaN
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16,NaN
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660,NaN
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456,84122.0

In [47]:
# Write code for repeating subtask 2 here
top10=movies.sort_values(by=['profit'],ascending=False).head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150000000.0,2015.0,7.0,150000,502177271.0
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,458672302.0
3024,George Lucas,282.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11000000.0,1977.0,8.7,33000,449935665.0
3080,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10500000.0,1982.0,7.9,34000,424449459.0
794,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
17,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
509,Roger Allers,186.0,422783777.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45000000.0,1994.0,8.5,17000,377783777.0
240,George Lucas,320.0,474544677.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115000000.0,1999.0,6.5,13000,359544677.0
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,348316061.0

-  Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.


    # Write your code for extracting the top 250 movies as per the IMDb score here.
    Make sure that you store it in a new dataframe
    # and name that dataframe as 'IMDb_Top_250'

Top_Foreign_Lang_Film = # Write your code to extract top foreign language films from 'IMDb_Top_250' here

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

In [48]:
movies.isnull().sum()

director_name              102
num_critic_for_reviews      46
gross                      880
genres                       0
actor_1_name                 7
movie_title                  0
num_voted_users              0
num_user_for_reviews        17
language                     0
budget                     488
title_year                 104
imdb_score                   0
movie_facebook_likes         0
profit                    1148
dtype: int64

In [49]:
# stored top 250 movies with highest imdb rating in new dataframe IMDb_top_250
IMDb_Top_250= movies.sort_values(by=['imdb_score'],ascending=False).head(250)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
2765,John Blanchard,NaN,NaN,Comedy,Martin Short,Towering Inferno,10,NaN,English,NaN,NaN,9.5,0,NaN
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,3341469.0
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,128821952.0
2824,NaN,53.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,37.0,Polish,NaN,NaN,9.1,0,NaN
4409,John Stockwell,2.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,1.0,English,17000000.0,2016.0,9.1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4348,Jehane Noujaim,68.0,NaN,Documentary|Drama|History|News,Khalid Abdalla,The Square,6678,42.0,Arabic,1500000.0,2013.0,8.1,0,NaN
179,Alejandro G. Iñárritu,556.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,48635922.0
2594,NaN,20.0,NaN,Comedy|Crime|Drama,Steven Van Zandt,Lilyhammer,19164,79.0,English,34000000.0,NaN,8.1,16000,NaN
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10000000.0,2004.0,8.1,0,-7913655.0
1213,Frank Miller,374.0,74098862.0,Crime|Thriller,Rosario Dawson,Sin City,656640,1732.0,English,40000000.0,2005.0,8.1,13000,34098862.0

In [50]:
# checking for all these movies,num_voted_users is greater than 25000
IMDb_Top_250.loc[(IMDb_Top_250.num_voted_users>25000),:]
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
2765,John Blanchard,NaN,NaN,Comedy,Martin Short,Towering Inferno,10,NaN,English,NaN,NaN,9.5,0,NaN
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,3341469.0
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,128821952.0
2824,NaN,53.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,37.0,Polish,NaN,NaN,9.1,0,NaN
4409,John Stockwell,2.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,1.0,English,17000000.0,2016.0,9.1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4348,Jehane Noujaim,68.0,NaN,Documentary|Drama|History|News,Khalid Abdalla,The Square,6678,42.0,Arabic,1500000.0,2013.0,8.1,0,NaN
179,Alejandro G. Iñárritu,556.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,48635922.0
2594,NaN,20.0,NaN,Comedy|Crime|Drama,Steven Van Zandt,Lilyhammer,19164,79.0,English,34000000.0,NaN,8.1,16000,NaN
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10000000.0,2004.0,8.1,0,-7913655.0
1213,Frank Miller,374.0,74098862.0,Crime|Thriller,Rosario Dawson,Sin City,656640,1732.0,English,40000000.0,2005.0,8.1,13000,34098862.0

In [51]:
# Add a new column 'Rank' ranging from 1 to 251 indicate the ranks of the corresponding films
IMDb_Top_250['Rank']=range(1,251)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
2765,John Blanchard,NaN,NaN,Comedy,Martin Short,Towering Inferno,10,NaN,English,NaN,NaN,9.5,0,NaN,1
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,3341469.0,2
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,128821952.0,3
2824,NaN,53.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,37.0,Polish,NaN,NaN,9.1,0,NaN,4
4409,John Stockwell,2.0,NaN,Action,Matthew Ziff,Kickboxer: Vengeance,246,1.0,English,17000000.0,2016.0,9.1,0,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4348,Jehane Noujaim,68.0,NaN,Documentary|Drama|History|News,Khalid Abdalla,The Square,6678,42.0,Arabic,1500000.0,2013.0,8.1,0,NaN,246
179,Alejandro G. Iñárritu,556.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,48635922.0,247
2594,NaN,20.0,NaN,Comedy|Crime|Drama,Steven Van Zandt,Lilyhammer,19164,79.0,English,34000000.0,NaN,8.1,16000,NaN,248
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10000000.0,2004.0,8.1,0,-7913655.0,249
1213,Frank Miller,374.0,74098862.0,Crime|Thriller,Rosario Dawson,Sin City,656640,1732.0,English,40000000.0,2005.0,8.1,13000,34098862.0,250

In [52]:
# Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film =IMDb_Top_250.loc[(IMDb_Top_250.language != 'English'),:]
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
2824,NaN,53.0,447093.0,Drama,Krystyna Janda,Dekalog,12590,37.0,Polish,NaN,NaN,9.1,0,NaN,4
3207,NaN,53.0,447093.0,Drama,Krystyna Janda,Dekalog,12591,37.0,Polish,NaN,NaN,9.1,0,NaN,6
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e+06,1966.0,8.9,20000,4.900000e+06,12
4029,Fernando Meirelles,214.0,7563397.0,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000e+06,2002.0,8.7,28000,4.263397e+06,27
3579,NaN,10.0,NaN,Crime|Drama|Thriller,Maria Pia Calzone,Gomorrah,9638,25.0,Italian,NaN,NaN,8.7,0,NaN,30
4747,Akira Kurosawa,153.0,269061.0,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000e+06,1954.0,8.7,11000,-1.730939e+06,34
2373,Hayao Miyazaki,246.0,10049886.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000e+07,2001.0,8.6,28000,-8.950114e+06,39
3870,Raja Menon,39.0,NaN,Action|Drama|History|Thriller|War,Nimrat Kaur,Airlift,30977,178.0,Hindi,4.400000e+06,2016.0,8.5,10000,NaN,55
4921,Majid Majidi,46.0,925402.0,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,1.800000e+05,1997.0,8.5,0,7.454020e+05,70
4259,Florian Henckel von Donnersmarck,215.0,11284657.0,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000e+06,2006.0,8.5,39000,9.284657e+06,72
2970,Wolfgang Petersen,96.0,11433134.0,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000e+07,1981.0,8.4,11000,-2.566866e+06,75
3685,Rakeysh Omprakash Mehra,33.0,2197331.0,Comedy|Drama|History|Romance,Anupam Kher,Rang De Basanti,70233,321.0,Hindi,NaN,2006.0,8.4,0,NaN,78
1329,S.S. Rajamouli,44.0,6498000.0,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615e+07,2015.0,8.4,21000,-1.152815e+07,82
1298,Jean-Pierre Jeunet,242.0,33201661.0,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000e+07,2001.0,8.4,39000,-4.379834e+07,85
4105,Chan-wook Park,305.0,2181290.0,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000e+06,2003.0,8.4,43000,-8.187100e+05,90
4659,Asghar Farhadi,354.0,7098492.0,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,5.000000e+05,2011.0,8.4,48000,6.598492e+06,99
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,11000,-2.397702e+09,101
1133,NaN,23.0,NaN,Drama|Fantasy|Horror|Mystery,Pierre Perrier,The Returned,15762,47.0,French,NaN,NaN,8.3,17000,NaN,109
4033,Thomas Vinterberg,349.0,610968.0,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000e+06,2012.0,8.3,60000,-3.189032e+06,113
2829,Oliver Hirschbiegel,192.0,5501940.0,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000e+07,2004.0,8.3,14000,-7.998060e+06,115
2734,Fritz Lang,260.0,26435.0,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000e+06,1927.0,8.3,12000,-5.973565e+06,117
4160,Rajkumar Hirani,15.0,NaN,Comedy|Drama|Romance,Vidya Balan,Lage Raho Munna Bhai,27569,106.0,Hindi,1.200000e+08,2006.0,8.2,349,NaN,149
1710,NaN,16.0,NaN,Crime|Drama|Thriller,Ólafur Darri Ólafsson,Trapped,2308,19.0,Icelandic,NaN,NaN,8.2,0,NaN,150
3550,Denis Villeneuve,226.0,6857096.0,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000e+06,2010.0,8.2,37000,5.709600e+04,152
4000,Juan José Campanella,262.0,20167424.0,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000e+06,2009.0,8.2,33000,1.816742e+07,158
204,Hideaki Anno,1.0,NaN,Action|Adventure|Drama|Horror|Sci-Fi,Mark Chinnery,Godzilla Resurgence,374,13.0,Japanese,NaN,2016.0,8.2,0,NaN,159
4945,Amal Al-Agroobi,NaN,NaN,Documentary|Family,NaN,The Brain That Sings,18,NaN,Arabic,1.250000e+05,2013.0,8.2,54,NaN,160
2047,Hayao Miyazaki,212.0,4710455.0,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000e+07,2004.0,8.2,13000,-1.928954e+07,165
4585,Joshua Oppenheimer,248.0,484221.0,Biography|Crime|Documentary|History,Anwar Congo,The Act of Killing,23836,107.0,Indonesian,1.000000e+06,2012.0,8.2,20000,-5.157790e+05,170
4809,Ingmar Bergman,76.0,NaN,Drama,Liv Ullmann,Cries & Whispers,19964,197.0,Swedish,4.000000e+05,1972.0,8.2,0,NaN,177
98,Hideaki Anno,1.0,NaN,Action|Adventure|Drama|Horror|Sci-Fi,Mark Chinnery,Godzilla Resurgence,374,13.0,Japanese,NaN,2016.0,8.2,0,NaN,178
2551,Guillermo del Toro,406.0,37623143.0,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000e+07,2006.0,8.2,27000,2.412314e+07,183
4461,Thomas Vinterberg,98.0,1647780.0,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000e+06,1998.0,8.1,5000,3.477800e+05,189
2914,Je-kyu Kang,86.0,1110186.0,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.280000e+07,2004.0,8.1,0,-1.168981e+07,196
2870,Niels Arden Oplev,NaN,NaN,Action|Crime|Mystery|Thriller,Michael Nyqvist,Del 1 - Män som hatar kvinnor,335,NaN,Swedish,NaN,NaN,8.1,22,NaN,199
3423,Katsuhiro Ôtomo,150.0,439162.0,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1.100000e+09,1988.0,8.1,0,-1.099561e+09,207
4682,Bernardo Bertolucci,120.0,NaN,Drama,Jean-Louis Trintignant,The Conformist,17813,101.0,Italian,7.500000e+05,1970.0,8.1,0,NaN,216
3553,José Padilha,142.0,8060.0,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000e+06,2007.0,8.1,11000,-3.991940e+06,217
4912,Carl Theodor Dreyer,54.0,NaN,Drama|Fantasy,Hanne Aagesen,Ordet,9903,49.0,Danish,NaN,1955.0,8.1,863,NaN,220
4267,Alejandro G. Iñárritu,157.0,5383834.0,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000e+06,2000.0,8.1,11000,3.383834e+06,244
4348,Jehane Noujaim,68.0,NaN,Documentary|Drama|History|News,Khalid Abdalla,The Square,6678,42.0,Arabic,1.500000e+06,2013.0,8.1,0,NaN,246
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,1.000000e+07,2004.0,8.1,0,-7.913655e+06,249

- Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.


    Write your code for extracting the top 10 directors here


**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

In [53]:
movies.isnull().sum()
bestdir=movies['director_name'].sort_values(ascending=False).head(10)
bestdir

4848         Étienne Faure
4191          Éric Tessier
3678      Émile Gaudreault
3242    Álex de la Iglesia
4887         Zoran Lisinac
3569        Zal Batmanglij
4944        Zal Batmanglij
4452              Zak Penn
4215         Zackary Adler
2461             Zack Ward
Name: director_name, dtype: object

In [54]:
# Write your code for extracting the top 10 directors here
top10director=movies.groupby('director_name')['imdb_score'].mean().sort_values(ascending=False).head(10)
top10director

director_name
John Blanchard      9.5
Cary Bell           8.7
Mitchell Altieri    8.7
Sadyk Sher-Niyaz    8.7
Charles Chaplin     8.6
Mike Mayhall        8.6
Ron Fricke          8.5
Majid Majidi        8.5
Damien Chazelle     8.5
Raja Menon          8.5
Name: imdb_score, dtype: float64

-  Subtask 3.6: Find popular genres

   You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

  1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
  2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
  3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.


    Write your code for extracting the first two genres of each movie here


movies_by_segment = # Write your code for grouping the dataframe here
PopGenre = # Write your code for getting the 5 most popular combo of genres here

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

In [55]:
# Write your code for extracting the first two genres of each movie here
first=movies['genres'].apply(lambda x: pd.Series(x.split('|')))
movies['genre_1']=first[0]
movies['genre_2']=first[1]
movies.loc[pd.isnull(movies['genre_2']), ['genre_2']] = movies['genre_1']
print(movies.genre_1)

0            Action
1            Action
2            Action
3            Action
5            Action
           ...
5038         Comedy
5039          Crime
5040          Drama
5041         Comedy
5042    Documentary
Name: genre_1, Length: 5039, dtype: object

In [56]:
print(movies.genre_2)

0         Adventure
1         Adventure
2         Adventure
3          Thriller
5         Adventure
           ...
5038          Drama
5039          Drama
5040         Horror
5041          Drama
5042    Documentary
Name: genre_2, Length: 5039, dtype: object

In [57]:
movies_by_segment =movies.groupby(['genre_1','genre_2']) # Write your code for grouping the dataframe here
movies_by_segment

In [59]:
gen =movies_by_segment['gross'].mean().sort_values(ascending=False).head(5) # Write your code for getting the 5 most popular combo of genres here
gen

genre_1    genre_2
Family     Sci-Fi       4.349495e+08
Adventure  Sci-Fi       2.286278e+08
           Animation    1.170500e+08
           Family       1.132994e+08
Action     Adventure    1.095400e+08
Name: gross, dtype: float64

-  Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.


    Write your code for creating three new dataframes here


   1. Meryl_Streep = # Include all movies in which Meryl_Streep is the lead
   2. Leo_Caprio = # Include all movies in which Leo_Caprio is the lead
   3. Brad_Pitt = # Include all movies in which Brad_Pitt is the lead
    
    A. Write your code for combining the three dataframes here
    B. Write your code for grouping the combined dataframe here
    C.  Write the code for finding the mean of critic reviews and audience reviews here

**Checkpoint 6:** `Leonardo` has aced both the lists!

In [60]:
# Include all movies in which Meryl_Streep is the lead
Meryl_Streep=movies.loc[(movies.actor_1_name=='Meryl Streep'),:].head(3891)
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
410,Nancy Meyers,187.0,112703470.0,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,27703470.0,Comedy,Drama
1106,Curtis Hanson,42.0,46815748.0,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,1815748.0,Action,Adventure
1204,Nora Ephron,252.0,94125426.0,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,54125426.0,Biography,Drama
1408,David Frankel,208.0,124732962.0,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,89732962.0,Comedy,Drama
1483,Robert Redford,227.0,14998070.0,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,-20001930.0,Drama,Thriller
1575,Sydney Pollack,66.0,87100000.0,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,56100000.0,Biography,Drama
1618,David Frankel,234.0,63536011.0,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,33536011.0,Comedy,Drama
1674,Carl Franklin,64.0,23209440.0,Drama,Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,-6790560.0,Drama,Drama
1752,Stephen Frears,87.0,NaN,Biography|Comedy|Drama|Music|Romance,Meryl Streep,Florence Foster Jenkins,2167,32.0,English,29000000.0,2016.0,7.1,0,NaN,Biography,Comedy
1925,Stephen Daldry,174.0,41597830.0,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,16597830.0,Drama,Romance
2781,Phyllida Lloyd,331.0,29959436.0,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,16959436.0,Biography,Drama
3135,Robert Altman,211.0,20338609.0,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,10338609.0,Comedy,Drama
3641,Fred Zinnemann,38.0,NaN,Drama,Meryl Streep,Julia,6454,44.0,English,7840000.0,1977.0,7.4,733,NaN,Drama,Drama

In [61]:
# Include all movies in which Leo_Caprio is the lead
Leo_Caprio=movies.loc[(movies.actor_1_name=='Leonardo DiCaprio'),:].head(3891)
Leo_Caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,458672302.0,Drama,Romance
50,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,39812796.0,Drama,Romance
97,Christopher Nolan,642.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,132568851.0,Action,Adventure
179,Alejandro G. Iñárritu,556.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,48635922.0,Adventure,Drama
257,Martin Scorsese,267.0,102608827.0,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,-7391173.0,Biography,Drama
296,Quentin Tarantino,765.0,162804648.0,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,62804648.0,Drama,Western
307,Edward Zwick,166.0,57366262.0,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,-42633738.0,Adventure,Drama
308,Martin Scorsese,606.0,116866727.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,16866727.0,Biography,Comedy
326,Martin Scorsese,233.0,77679638.0,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,-22320362.0,Crime,Drama
361,Martin Scorsese,352.0,132373442.0,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,42373442.0,Crime,Drama
452,Martin Scorsese,490.0,127968405.0,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,47968405.0,Mystery,Thriller
641,Ridley Scott,238.0,39380442.0,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,-30619558.0,Action,Drama
911,Steven Spielberg,194.0,164435221.0,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,112435221.0,Biography,Crime
990,Danny Boyle,118.0,39778599.0,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,-10221401.0,Adventure,Drama
1114,Sam Mendes,323.0,22877808.0,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,-12122192.0,Drama,Romance
1422,Randall Wallace,83.0,56876365.0,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,21876365.0,Action,Adventure
1453,Clint Eastwood,392.0,37304950.0,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,2304950.0,Biography,Crime
1560,Sam Raimi,63.0,18636537.0,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,-13363463.0,Action,Thriller
2067,Jerry Zaks,45.0,12782508.0,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,-10217492.0,Drama,Drama
2757,Baz Luhrmann,106.0,46338728.0,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,31838728.0,Drama,Romance
3476,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,39812796.0,Drama,Romance

In [62]:
# Include all movies in which Brad_Pitt is the lead
Brad_Pitt=movies.loc[(movies.actor_1_name=='Brad Pitt'),:].head(3891)
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
101,David Fincher,362.0,127490802.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,-22509198.0,Drama,Fantasy
147,Wolfgang Petersen,220.0,133228348.0,Adventure,Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,-41771652.0,Adventure,Adventure
254,Steven Soderbergh,198.0,125531634.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,15531634.0,Crime,Thriller
255,Doug Liman,233.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,66336103.0,Action,Comedy
382,Tony Scott,142.0,26871.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,-91973129.0,Action,Crime
400,Steven Soderbergh,186.0,183405771.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,98405771.0,Crime,Thriller
470,David Ayer,406.0,85707116.0,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,17707116.0,Action,Drama
611,Jean-Jacques Annaud,76.0,37901509.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,-32098491.0,Adventure,Biography
683,David Fincher,315.0,37023395.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,-25976605.0,Drama,Drama
792,Patrick Gilmore,98.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,-33711680.0,Adventure,Animation
940,Neil Jordan,120.0,105264608.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,45264608.0,Drama,Fantasy
1490,Terrence Malick,584.0,13303319.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,-18696681.0,Drama,Fantasy
1722,Andrew Dominik,273.0,3904982.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,-26095018.0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34300771.0,Drama,Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,9300771.0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,531009.0,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,-9468991.0,Drama,Romance
2682,Andrew Dominik,414.0,14938570.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,-61430.0,Crime,Thriller
2898,Tony Scott,122.0,12281500.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,-718500.0,Action,Crime
4749,Tom DiCillo,10.0,NaN,Comedy|Music|Romance,Brad Pitt,Johnny Suede,3013,24.0,English,500000.0,1991.0,5.8,344,NaN,Comedy,Music

In [66]:
# Write your code for combining the three dataframes here
Combined = pd.concat([Meryl_Streep, Leo_Caprio, Brad_Pitt], ignore_index=True)
Combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
0,Nancy Meyers,187.0,112703470.0,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,27703470.0,Comedy,Drama
1,Curtis Hanson,42.0,46815748.0,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,1815748.0,Action,Adventure
2,Nora Ephron,252.0,94125426.0,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,54125426.0,Biography,Drama
3,David Frankel,208.0,124732962.0,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,89732962.0,Comedy,Drama
4,Robert Redford,227.0,14998070.0,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,-20001930.0,Drama,Thriller
5,Sydney Pollack,66.0,87100000.0,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,56100000.0,Biography,Drama
6,David Frankel,234.0,63536011.0,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,33536011.0,Comedy,Drama
7,Carl Franklin,64.0,23209440.0,Drama,Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,-6790560.0,Drama,Drama
8,Stephen Frears,87.0,NaN,Biography|Comedy|Drama|Music|Romance,Meryl Streep,Florence Foster Jenkins,2167,32.0,English,29000000.0,2016.0,7.1,0,NaN,Biography,Comedy
9,Stephen Daldry,174.0,41597830.0,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,16597830.0,Drama,Romance
10,Phyllida Lloyd,331.0,29959436.0,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,16959436.0,Biography,Drama
11,Robert Altman,211.0,20338609.0,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,10338609.0,Comedy,Drama
12,Fred Zinnemann,38.0,NaN,Drama,Meryl Streep,Julia,6454,44.0,English,7840000.0,1977.0,7.4,733,NaN,Drama,Drama
13,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,458672302.0,Drama,Romance
14,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,39812796.0,Drama,Romance
15,Christopher Nolan,642.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,132568851.0,Action,Adventure
16,Alejandro G. Iñárritu,556.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,48635922.0,Adventure,Drama
17,Martin Scorsese,267.0,102608827.0,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,-7391173.0,Biography,Drama
18,Quentin Tarantino,765.0,162804648.0,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,62804648.0,Drama,Western
19,Edward Zwick,166.0,57366262.0,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,-42633738.0,Adventure,Drama
20,Martin Scorsese,606.0,116866727.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,16866727.0,Biography,Comedy
21,Martin Scorsese,233.0,77679638.0,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,-22320362.0,Crime,Drama
22,Martin Scorsese,352.0,132373442.0,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,42373442.0,Crime,Drama
23,Martin Scorsese,490.0,127968405.0,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,47968405.0,Mystery,Thriller
24,Ridley Scott,238.0,39380442.0,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,-30619558.0,Action,Drama
25,Steven Spielberg,194.0,164435221.0,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,112435221.0,Biography,Crime
26,Danny Boyle,118.0,39778599.0,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,-10221401.0,Adventure,Drama
27,Sam Mendes,323.0,22877808.0,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,-12122192.0,Drama,Romance
28,Randall Wallace,83.0,56876365.0,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,21876365.0,Action,Adventure
29,Clint Eastwood,392.0,37304950.0,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,2304950.0,Biography,Crime
30,Sam Raimi,63.0,18636537.0,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,-13363463.0,Action,Thriller
31,Jerry Zaks,45.0,12782508.0,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,-10217492.0,Drama,Drama
32,Baz Luhrmann,106.0,46338728.0,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,31838728.0,Drama,Romance
33,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,39812796.0,Drama,Romance
34,David Fincher,362.0,127490802.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,-22509198.0,Drama,Fantasy
35,Wolfgang Petersen,220.0,133228348.0,Adventure,Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,-41771652.0,Adventure,Adventure
36,Steven Soderbergh,198.0,125531634.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,15531634.0,Crime,Thriller
37,Doug Liman,233.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,66336103.0,Action,Comedy
38,Tony Scott,142.0,26871.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,-91973129.0,Action,Crime
39,Steven Soderbergh,186.0,183405771.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,98405771.0,Crime,Thriller
40,David Ayer,406.0,85707116.0,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,17707116.0,Action,Drama
41,Jean-Jacques Annaud,76.0,37901509.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,-32098491.0,Adventure,Biography
42,David Fincher,315.0,37023395.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,-25976605.0,Drama,Drama
43,Patrick Gilmore,98.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,-33711680.0,Adventure,Animation
44,Neil Jordan,120.0,105264608.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,45264608.0,Drama,Fantasy
45,Terrence Malick,584.0,13303319.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,-18696681.0,Drama,Fantasy
46,Andrew Dominik,273.0,3904982.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,-26095018.0,Biography,Crime
47,Alejandro G. Iñárritu,285.0,34300771.0,Drama,Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,9300771.0,Drama,Drama
48,Angelina Jolie Pitt,131.0,531009.0,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,-9468991.0,Drama,Romance
49,Andrew Dominik,414.0,14938570.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,-61430.0,Crime,Thriller
50,Tony Scott,122.0,12281500.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,-718500.0,Action,Crime
51,Tom DiCillo,10.0,NaN,Comedy|Music|Romance,Brad Pitt,Johnny Suede,3013,24.0,English,500000.0,1991.0,5.8,344,NaN,Comedy,Music

In [67]:
# Write your code for grouping the combined dataframe here
actor_name=Combined.groupby('actor_1_name')   # grouping the Combined dataframe using actor_1_name and store it in new dataframe actor_name
actor_name

In [68]:
# Write the code for finding the mean of critic reviews and audience reviews here
critic_reviews=actor_name['num_critic_for_reviews'].mean().sort_values(ascending=False).head(49)
print(critic_reviews)
audience_reviews=actor_name['num_user_for_reviews'].mean().sort_values(ascending=False).head(49)
print(audience_reviews)

actor_1_name
Leonardo DiCaprio    330.190476
Brad Pitt            231.944444
Meryl Streep         163.153846
Name: num_critic_for_reviews, dtype: float64
actor_1_name
Leonardo DiCaprio    914.476190
Brad Pitt            702.444444
Meryl Streep         257.307692
Name: num_user_for_reviews, dtype: float64